#!/bin/bash

case $tikt_hook in
	"before:command:clean" | "before:command:truncate" )
		echo "WIPING FILES BLANK"
		clean_files=$(tikt_var_replace ${files[@]})
		for file in ${clean_files[@]}
		do
			if [ -f $file ]; then
				echo '' > $file
			fi
		done
		exit
	;;
esac
