#!/bin/bash

case $tikt_hook in
	"after:tikt:edit")
		php_files=$(tikt_var_replace ${files[@]})
		for file in ${php_files[@]}
		do
			if [[ "${file##*.}" == "php" ]]; then
				php -l $file
			fi
		done
	;;
esac

